# -*- coding: utf-8 -*-
"""Career Path Recommendations Using Skill Profiling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XDVh3V-D-I6YmbMWL9muiMgiGAS3ELge
"""

# Colab cell 1: install required libraries
!pip install -q flask pyngrok sentence-transformers pandas scikit-learn PyPDF2



# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import os
# from flask import Flask, request, render_template
# from werkzeug.utils import secure_filename
# from sentence_transformers import SentenceTransformer
# import pandas as pd
# from sklearn.metrics.pairwise import cosine_similarity
# import numpy as np
# import PyPDF2
# 
# UPLOAD_FOLDER = "uploads"
# ALLOWED_EXTENSIONS = {"pdf", "txt"}
# 
# app = Flask(__name__)
# app.config["UPLOAD_FOLDER"] = UPLOAD_FOLDER
# os.makedirs(UPLOAD_FOLDER, exist_ok=True)
# 
# # Load model
# print("Loading SentenceTransformer model...")
# model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")
# print("✅ Model loaded successfully.")
# 
# # Load your dataset
# dataset_path = "/content/all_job_post.csv"
# try:
#     roles_df = pd.read_csv(dataset_path)
#     print(f"✅ Loaded dataset with {len(roles_df)} rows.")
# except Exception as e:
#     raise SystemExit(f"❌ Failed to load dataset: {e}")
# 
# # Prepare skill embeddings
# roles_df["skills"] = roles_df["skills"].fillna("").apply(
#     lambda s: [x.strip().lower() for x in str(s).split(",") if x.strip()]
# )
# roles_df["skill_text"] = roles_df["skills"].apply(lambda s: " ".join(s))
# role_embeddings = model.encode(roles_df["skill_text"].tolist(), convert_to_numpy=True)
# 
# def allowed_file(filename):
#     return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS
# 
# def extract_text_from_pdf(path):
#     text = ""
#     try:
#         with open(path, "rb") as f:
#             reader = PyPDF2.PdfReader(f)
#             for page in reader.pages:
#                 page_text = page.extract_text()
#                 if page_text:
#                     text += page_text + "\n"
#     except Exception as e:
#         print("PDF error:", e)
#     return text
# 
# def simple_skill_extractor(text, skill_vocab):
#     text_l = text.lower()
#     found = set()
#     for kw in skill_vocab:
#         if kw in text_l:
#             found.add(kw)
#     return sorted(found)
# 
# def recommend_roles(user_skills, top_k=3):
#     user_text = " ".join(user_skills)
#     user_emb = model.encode([user_text], convert_to_numpy=True)
#     sims = cosine_similarity(user_emb, role_embeddings)[0]
#     idx = np.argsort(-sims)[:top_k]
#     results = []
#     for i in idx:
#         role = roles_df.iloc[i]
#         score = float(sims[i])
#         pct = round(max(0.0, score) * 100, 1)
#         req = set(role["skills"])
#         missing = sorted(list(req - set(user_skills)))
#         results.append({
#             "role": role["role"],
#             "match_pct": pct,
#             "missing_skills": missing,
#             "required_skills": sorted(list(req))
#         })
#     return results
# 
# @app.route("/", methods=["GET"])
# def index():
#     return render_template("index.html")
# 
# @app.route("/analyze", methods=["POST"])
# def analyze():
#     skills_input = request.form.get("skills_input", "").strip()
#     file = request.files.get("resume_file")
#     extracted_text = ""
#     user_skills = set()
# 
#     if skills_input:
#         for s in skills_input.replace(";", ",").split(","):
#             if s.strip():
#                 user_skills.add(s.strip().lower())
# 
#     if file and file.filename != "":
#         if allowed_file(file.filename):
#             filename = secure_filename(file.filename)
#             filepath = os.path.join(app.config["UPLOAD_FOLDER"], filename)
#             file.save(filepath)
#             if filename.endswith(".pdf"):
#                 extracted_text = extract_text_from_pdf(filepath)
#             else:
#                 with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
#                     extracted_text = f.read()
#             vocab = set([skill for lst in roles_df["skills"] for skill in lst])
#             found = simple_skill_extractor(extracted_text, vocab)
#             user_skills.update(found)
# 
#     if not user_skills:
#         return render_template("no_skills.html")
# 
#     recs = recommend_roles(sorted(user_skills))
#     return render_template("results.html", user_skills=sorted(user_skills), recommendations=recs)
# 
# @app.route("/health")
# def health():
#     return "OK"
# 
# if __name__ == "__main__":
#     app.run(host="0.0.0.0", port=8000, debug=False)
#

import os
os.makedirs("templates", exist_ok=True)

# ---------- index.html ----------
index_html = """<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Career Recommender</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
    <style>
      body {
        font-family: 'Poppins', sans-serif;
        margin: 0;
        padding: 0;
        background: linear-gradient(135deg, #74ABE2, #5563DE);
        min-height: 100vh;
        display: flex;
        align-items: center;
        justify-content: center;
        color: #333;
      }
      .container {
        background: #fff;
        border-radius: 16px;
        box-shadow: 0 6px 20px rgba(0,0,0,0.1);
        padding: 40px 50px;
        max-width: 700px;
        width: 90%;
        text-align: center;
      }
      h1 {
        color: #2E3B55;
        margin-bottom: 15px;
      }
      p {
        color: #555;
        font-size: 15px;
      }
      textarea {
        width: 100%;
        height: 100px;
        border-radius: 10px;
        border: 1px solid #ccc;
        padding: 10px;
        font-size: 15px;
        resize: none;
        transition: all 0.2s;
      }
      textarea:focus {
        border-color: #5563DE;
        box-shadow: 0 0 5px rgba(85,99,222,0.4);
        outline: none;
      }
      input[type=file] {
        margin-top: 10px;
        font-size: 14px;
      }
      .btn {
        background: linear-gradient(135deg, #5563DE, #74ABE2);
        color: white;
        border: none;
        border-radius: 10px;
        padding: 12px 30px;
        font-size: 16px;
        cursor: pointer;
        margin-top: 20px;
        transition: transform 0.2s ease, box-shadow 0.2s ease;
      }
      .btn:hover {
        transform: translateY(-2px);
        box-shadow: 0 6px 15px rgba(85,99,222,0.3);
      }
      footer {
        font-size: 13px;
        color: #666;
        margin-top: 25px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>🚀 Career Role Recommender</h1>
      <p>Get personalized career role suggestions based on your skills or resume.</p>
      <form action="/analyze" method="post" enctype="multipart/form-data">
        <label for="skills"><strong>Enter your skills:</strong></label><br>
        <textarea id="skills" name="skills_input" placeholder="e.g., Python, SQL, Tableau"></textarea><br><br>
        <label for="resume"><strong>Or upload your resume (PDF/TXT):</strong></label><br>
        <input type="file" id="resume" name="resume_file" accept=".pdf,.txt"><br><br>
        <button type="submit" class="btn">✨ Get Recommendations</button>
      </form>
      <footer>
        Powered by <strong>Sentence Transformers</strong> · Designed for Career Growth 🌱
      </footer>
    </div>
  </body>
</html>
"""
with open("templates/index.html","w",encoding="utf-8") as f:
    f.write(index_html)


# ---------- results.html ----------
results_html = """<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Career Recommendations</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
    <style>
      body {
        font-family: 'Poppins', sans-serif;
        background: linear-gradient(135deg, #74ABE2, #5563DE);
        color: #333;
        margin: 0;
        padding: 40px 0;
      }
      .container {
        background: #fff;
        border-radius: 16px;
        box-shadow: 0 6px 20px rgba(0,0,0,0.15);
        padding: 40px;
        max-width: 900px;
        margin: auto;
      }
      h1 {
        text-align: center;
        color: #2E3B55;
      }
      .badge {
        display: inline-block;
        background: #5563DE;
        color: #fff;
        padding: 6px 12px;
        border-radius: 20px;
        margin: 3px;
        font-size: 14px;
      }
      .card {
        background: #f9f9ff;
        border-left: 6px solid #5563DE;
        border-radius: 10px;
        padding: 20px;
        margin-bottom: 20px;
        transition: transform 0.2s ease;
      }
      .card:hover { transform: translateY(-3px); }
      .role-title {
        color: #2E3B55;
        margin-bottom: 10px;
      }
      a.back {
        display: inline-block;
        margin-top: 20px;
        text-decoration: none;
        background: #5563DE;
        color: white;
        padding: 10px 20px;
        border-radius: 8px;
      }
      a.back:hover { background: #3943C2; }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>🎯 Your Career Recommendations</h1>
      <h3>Extracted/Entered Skills:</h3>
      {% for s in user_skills %}
        <span class="badge">{{ s }}</span>
      {% endfor %}
      <hr>
      {% for r in recommendations %}
        <div class="card">
          <h3 class="role-title">{{ r.role }} — {{ r.match_pct }}% match</h3>
          <p><strong>Required skills:</strong> {{ r.required_skills | join(', ') }}</p>
          <p><strong>Missing skills:</strong> {% if r.missing_skills %} {{ r.missing_skills | join(', ') }} {% else %} None {% endif %}</p>
          <p><strong>Suggestion:</strong> {{ r.feedback }}</p>
        </div>
      {% endfor %}
      <center><a href="/" class="back">⬅ Back</a></center>
    </div>
  </body>
</html>
"""
with open("templates/results.html","w",encoding="utf-8") as f:
    f.write(results_html)


# ---------- no_skills.html ----------
no_skills_html = """<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>No Skills Found</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
    <style>
      body {
        font-family: 'Poppins', sans-serif;
        background: linear-gradient(135deg, #74ABE2, #5563DE);
        color: #fff;
        text-align: center;
        padding: 100px 20px;
      }
      .box {
        background: rgba(255,255,255,0.15);
        border-radius: 20px;
        padding: 40px;
        max-width: 500px;
        margin: auto;
        box-shadow: 0 4px 10px rgba(0,0,0,0.2);
      }
      a {
        display: inline-block;
        margin-top: 20px;
        color: #fff;
        text-decoration: none;
        background: #2E3B55;
        padding: 10px 20px;
        border-radius: 10px;
      }
      a:hover { background: #1f2845; }
    </style>
  </head>
  <body>
    <div class="box">
      <h1>⚠️ No Skills Detected</h1>
      <p>We couldn’t detect any skills from your input.<br>Try entering them manually (e.g., “Python, SQL”) or upload a clearer resume.</p>
      <a href="/">⬅ Back</a>
    </div>
  </body>
</html>
"""
with open("templates/no_skills.html","w",encoding="utf-8") as f:
    f.write(no_skills_html)

print("✨ Modern UI templates created successfully.")

# Colab cell 2: stop previous runs (safe to run)
!pkill -f flask || echo "No flask running"
!pkill -f ngrok || echo "No ngrok running"

# ✅ Check if port 8000 is occupied
!lsof -i :8000 || echo "Port 8000 is free"

# (Optional) If any PID shows up in the above output, kill it:
!kill -9 4368

# ✅ Run Flask in the background and log output
!nohup python app.py > flask.log 2>&1 &

!tail -n 50 flask.log

# Colab cell 5: show a quick tree
!ls -R

# Colab cell 6: run the Flask app in background and log output
# Use nohup so it survives the cell completion. Background the process.
!nohup python app.py > flask.log 2>&1 &
# show last lines of log (may be empty until model loaded)
!sleep 1 && tail -n 30 flask.log

# Colab cell 7: start ngrok tunnel and show public URL
from pyngrok import ngrok, conf
# If you have an auth token, set it here. If you prefer to set via environment variable, do that instead.
conf.get_default().auth_token = "345QO4rgr00ARzL1WTwD44ltomA_7zUWjh8GD1cJtLAhbqMuA"  # <--- replace if you want
public_url = ngrok.connect(8000)
print("🌍 Public URL:", public_url)
print("Open this URL in a browser. Append /health to test quickly (eg. <url>/health).")